<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN""http://www.w3.org/TR/html4/loose.dtd"><html><head><title>Exception Handling</title><meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1"><style type="text/css"><!--.style8 {color: #000099}.style9 {font-family: "Courier New", Courier, mono}.style10 {	color: #FF6600;	font-weight: bold;}.style11 {color: #FF6600}--></style></head><body><? // grab the headerinclude 'notes-header.php' ; ?><h1 align="center" class="style8">Exception Handling </h1><p align="right"><font size="-1">Last Modified <!-- #BeginDate format:Am2 -->7/22/11<!-- #EndDate --></font></p><p align="center"><font size="1">		<a href="#idea">Overview</a> &bull; 		<a href="#trycatch">try...catch</a> &bull; 		<a href="#throws">throws</a> &bull; 		<a href="#finally">finally</a> &bull; 		<a href="#hierarchy">Exception Hierarchy</a> &bull; 		<a href="#stack">Stack Tracing</a> </font></p><hr><h2><font color="#990033"><a name="idea"></a></font><span class="style8">Overview</span></h2><p>Many things can go wrong in the course of executing a program, causing what we call <strong>exceptions</strong> to the normal flow of execution: </p><ul>  <li>Input could fail or we might not be able to produce output in various ways. This is an <span class="style9">IOException</span>.<ul><li>More specifically, we could try to read from a file that doesn't exist or isn't where we're looking for it. This is a <span class="style9">FileNotFoundException</span>.</li>    </ul>  </li>  <li>We could ask the user to input numeric data and get text. Data type problems like this constitute <span class="style9">InputMismatchException</span>s.</li>  <li>We could try to convert a <span class="style9">String</span> to a number, but that <span class="style9">String</span> doesn't store a number. This is a <span class="style9">NumberFormatException</span>.</li>  <li>Our program could be using some sort of reference data type and try to access an object that's not been constructed or a pointer that doesn't point to anything. This is a <span class="style9">NullPointerException</span>.</li>  <li>A user could input a zero value that ends up as the denominator of a fraction. This is an example of an <span class="style9">ArithmeticException</span>.</li>  <li>We could attempt to access an array element with index 20 or -2 when the array has 20 elements. These are <span class="style9">ArrayIndexOutOfBoundsException</span>s.</li></ul><p>We need to deal with these kinds of problems and refer to this process as <strong>exception handling</strong>. When an exception is encountered, we say that the system <strong>throws</strong> an exception. Dealing with the exception involves <strong>catching</strong> the exception and doing some kind of processing. </p><p>We'd like to write our programs in such a way that we're not always worrying about everything that can go wrong at every instant. Java's model of exception handling is to place all code that could throw exceptions in a block of code called a <strong>try block</strong>. Note that we generally have one try block that could throw multiple kinds of exceptions instead of giving each potentially problematic line its own try block. Following the try block, we have one or more <strong>catch blocks</strong> to deal with different kinds of exceptions. </p><p>Note that Java also defines a class called <span class="style9">Exception</span>, from which all kinds of exceptions inherit. Think of using class <span class="style9">Exception</span> as sort of a &quot;catch all.&quot; </p><p>&nbsp;</p><p>&nbsp;</p><p align="center"><font size="1"><a href="#idea">Overview</a> &bull; <a href="#trycatch">try...catch</a> &bull; <a href="#throws">throws</a> &bull; <a href="#finally">finally</a> &bull; <a href="#hierarchy">Exception Hierarchy</a> &bull; <a href="#stack">Stack Tracing</a> </font></p><hr><h2><font color="#990033"><a name="trycatch"></a></font><span class="style8">try...catch</span></h2><p>Here's the general form of a try...catch structure:</p><blockquote>  <pre><span class="style10">try{</span>    // Code that could throw exceptions<span class="style10">}</span><span class="style10">catch(</span> ExceptionType exceptionName <span class="style11"><strong>)</strong></span><span class="style11"><strong>{</strong></span>    // Code for handling this kind of exception<span class="style10">}catch(</span> ExceptionType exceptionName <span class="style10">){</span>    // Code for handling this kind of exception<span class="style11"><strong>}</strong></span>// More catch blocks? </pre></blockquote><p>&nbsp; </p><p>Notes:</p><ul>  <li>Only one argument can appear in the <span class="style9">catch</span> parentheses. When choosing a name, choose something that relates to the type of exception. (Abbreviations are fine, e.g. <span class="style9">Exception e</span>, <span class="style9">IOException ioe</span>.) </li>  <li>Only one catch block executes. </li>  <li>So, list the most specific kinds of exceptions first, and the most general exceptions last. </li>  <li>If you choose to include type <span class="style9">Exception</span>, put it last. </li>  <li>Code in the catch blocks could simply print error messages or could set up the program for reexecution. (Consider putting the try...catch in a loop and setting a boolean flag that is used for a loop test here.) </li>  <li>Avoid writing code in catch blocks that could throw exceptions. </li></ul><p>&nbsp;</p><p>Suppose we're working with an array of objects where each object contains one field that is a numeric rating. Here's an example containing a myriad of things that could go wrong:</p><blockquote>  <pre>try{   System.out.print(&quot;Enter an array index: &quot;);   numerIndex = input.nextInt();   System.out.print(&quot;Enter another array index: &quot;);   denomIndex = input.nextInt();      ratio = data[numerIndex].getRating()          / data[denomIndex].getRating();   System.out.println(data[numerIndex].getName()                     + &quot; is &quot; + ratio + &quot; times stronger than &quot;                    + data[denomIndex].getName()); }catch(InputMismatchException ime){   System.out.println(&quot;You must enter integers only for indices.&quot;);}catch(IOException ioe){   System.out.println(&quot;Some kind of input/output problem occurred.&quot;);}catch(NullPointerException npe){   System.out.println(&quot;No record exists at one of the entered indices.&quot;); }catch(ArrayIndexOutOfBoundsException aioobe){   System.out.println(&quot;You've entered an invalid array index.&quot;);   System.out.println(&quot;Please choose indices between 0 and &quot; +                          (data.length-1));}catch(ArithmeticExcpetion ae){    System.out.println(data[denomIndex].getName() + &quot;\'s rating is 0, &quot;                      + &quot;and it isn't possible to divide by 0.&quot;);    }catch(Exception e){    System.out.println(&quot;An unknown error occurred.&quot;); }</pre></blockquote><p>&nbsp;</p>Notice how we wrote our code assuming there would be no problems in the try block and dealt with the exceptions in the catch blocks later. <p>&nbsp;</p><p>&nbsp;</p><p align="center"><font size="1"><a href="#idea">Overview</a> &bull; <a href="#trycatch">try...catch</a> &bull; <a href="#throws">throws</a> &bull; <a href="#finally">finally</a> &bull; <a href="#hierarchy">Exception Hierarchy</a> &bull; <a href="#stack">Stack Tracing</a> </font> </p><hr><h2><font color="#990033"><a name="throws"></a></font><span class="style8">Methods: the  <span class="style9">throws</span> Clause </span></h2><p>When writing methods that have the potential to contain exceptions, we have two options:</p><ul>  <li>Handle the exceptions within the methods themselves.</li>  <li>Add a <span class="style9"><strong>throws</strong></span> clause to the end of the method header and handle the exception in the client code. </li></ul><p>Here's an example of moving the input phase of the above example into a method:</p><blockquote>  <pre>public void Input() <span class="style10">throws IOException</span>{   System.out.print(&quot;Enter an array index: &quot;);   numerIndex = input.nextInt();   System.out.print(&quot;Enter another array index: &quot;);   denomIndex = input.nextInt(); } </pre></blockquote><p>We would then simply call this method in the try block as we'd done before. (This assumes the variables have class-wide scope. </p><p>&nbsp;</p><p>&nbsp;</p><p align="center"><font size="1"><a href="#idea">Overview</a> &bull; <a href="#trycatch">try...catch</a> &bull; <a href="#throws">throws</a> &bull; <a href="#finally">finally</a> &bull; <a href="#hierarchy">Exception Hierarchy</a> &bull; <a href="#stack">Stack Tracing</a> </font></p><hr><h2><font color="#990033"><a name="finally"></a></font><span class="style8">The <span class="style9">finally</span> Block </span></h2><p>An optional part of exception handling is to add a <span class="style9">finally</span> block at the end of a try...catch structure:</p><blockquote>  <pre><span class="style10">try{</span>    // Code that could throw exceptions<span class="style10">}</span><span class="style10">catch(</span> ExceptionType exceptionName <span class="style11"><strong>)</strong></span><span class="style11"><strong>{</strong></span>    // Code for handling this kind of exception<span class="style10">}catch(</span> ExceptionType exceptionName <span class="style10">){</span>    // Code for handling this kind of exception<span class="style11"><strong>}</strong></span>// More catch blocks? <span class="style10">finally</span><span class="style10">{</span>    // Statements for wrapping up exception handling and     // freeing resources<span class="style11"><strong>}</strong></span></pre></blockquote><p>Note that there is only ever one <span class="style9">finally</span> block. We can use it for any closing kinds of statements (including terminating the program in dire situations). We can also use it for releasing resources that might have been opened. We'll see more reasons for this when we get into databases. It will always execute when the <span class="style9">try...catch</span> block ends, whether all of the code in <span class="style9">try</span> runs or whether an exception was thrown and a <span class="style9">catch</span> block runs. </p><p>&nbsp;</p><p>&nbsp;</p><p align="center"><font size="1"><a href="#idea">Overview</a> &bull; <a href="#trycatch">try...catch</a> &bull; <a href="#throws">throws</a> &bull; <a href="#finally">finally</a> &bull; <a href="#hierarchy">Exception Hierarchy</a> &bull; <a href="#stack">Stack Tracing</a> </font></p><hr><h2><font color="#990033"><a name="hierarchy"></a></font><span class="style8">Java Exception Hierarchy </span></h2><p>Inheritance comes into play with exceptions. The class <span class="style9">Exception</span> is a subclass of the superclass <span class="style9">Throwable</span>, which has another subclass <span class="style9">Error</span>. This is important due to the hierarchy of how exceptions are caught and the order in which we list <span class="style9">catch</span> statements. </p><p>Consider the following illustration, taken from Deitel: </p><blockquote>  <p><img src="exceptions-deitel.jpg" alt="Throwable heirarchy. Exception and Error are subclasses of Throwable. Subclasses of Error are AWTError, ThreadDeath, and OutOfMemoryError. IOException is a subclass of Exception. Another subclass of Exception is RuntimeException, which has subclasses ClassCastException, ArrayIndexOutOfBoundsException, NullPointerException, InputMismatchException, and ArithmeticExcpetion." width="526" height="331"></p></blockquote><p>&nbsp;</p><p>For more, see the <a href="http://java.sun.com/javase/6/docs/api/java/lang/Exception.html">Java API details on all defined Exceptions</a>. </p><p>&nbsp;</p><p>&nbsp;</p><p align="center"><font size="1"><a href="#idea">Overview</a> &bull; <a href="#trycatch">try...catch</a> &bull; <a href="#throws">throws</a> &bull; <a href="#finally">finally</a> &bull; <a href="#hierarchy">Exception Hierarchy</a> &bull; <a href="#stack">Stack Tracing</a> </font></p><hr><h2><font color="#990033"><a name="stack"></a></font><span class="style8">Exception Stack </span></h2><p>Java maintains a call stack, and one useful thing to do in handling exceptions is to print out a trace of the call stack to help locate where the problem occurred. You can do so using the Exception member function <span class="style9">printStackTrace()</span>. </p><p>Codewise, you might have this sort of <span class="style9">catch</span> block:</p><blockquote>  <pre>//...catch(Exception e){   e.printStackTrace();}</pre>  <p>&nbsp;</p></blockquote><p>If you'd like to store the call stack information, you can also use the method <span class="style9">getStackTrace()</span>, which returns an array of <span class="style9">StackTraceElement</span> objects. </p><p>Codewise, you might have this sort of <span class="style9">catch</span> block:</p><blockquote>  <pre>StackTraceElement[] trace//...catch(Exception e){   trace = e.getStackTrace();   for(StackTraceElement cur : trace)   {      System.out.println(cur.getClassName() + &quot; on &quot; + cur.getLineNumber());    }}</pre></blockquote><p>&nbsp;</p><p>&nbsp;</p><p>&nbsp;</p><p align="center"><font size="1"><a href="#idea">Overview</a> &bull; <a href="#trycatch">try...catch</a> &bull; <a href="#throws">throws</a> &bull; <a href="#finally">finally</a> &bull; <a href="#hierarchy">Exception Hierarchy</a> &bull; <a href="#stack">Stack Tracing</a> </font></p></body></html>